name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My first Github actions job"
        
        - name: Create File
          run: touch text-file.txt
        
        - name: add comment on the file
          run:  echo "Hello World" > test.txt
          
        - name: List Files
          run: ls

        - name: Read File
          run: cat text-file.txt
              