name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4
        
        - name: Create File
          run: rm test.txt 
        
        - name: Create File
          run: ls

        - name: Read File
          run: cat README.md
              