name: Generate Ascii Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: list files
          run: ls -ltr
        
        - name: Executing shell script
          run: |
             chmod +x ascii-script.sh   
             ./ascii-script.sh

