name: Generate Ascii Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          uses: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          uses: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

        - name: check if test file exists
          uses: grep -i "dragon" dragon.txt

        - name: Read file
          uses: cat dragon.txt

        - name: checkout repo files
          uses: ls -ltr