name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
    deploy:
      strategy:
        # fail-fast: false
        # max-parallel: 2
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          images: [hello-world, alpine]
          exclude:  # this will exclude windows-latest from running alpine image
            - images: alpine
              os: windows-latest
          include: # ensures 'amd64/alpine' image can only be run on 'ubuntu-20.04'
            - images: amd64/alpine
              os: ubuntu-20.04
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}